### ISSUE TITLE
About makepad book

### ISSUE THREAD

**Issue by kentaurse** [Project-Robius-China/makepad-book#4]
@tyreseluo how are you?
I m very interested this project.
Could you explain about this project?

**Comment by tyreseluo** [comment]
@kentaurse Hi!Nice to meet you! yes,of course.  The Book of Makepad, aimed at Makepad application developers and contributors, systematically introduces various aspects of the Rust cross-platform Makepad UI framework.

**Comment by kentaurse** [comment]
please invite me.

**Comment by tyreseluo** [comment]
@kentaurse Sorry, i don't know what your problem is so i close the issue.
